image: ruby:2.7.6

services:
  - postgres:12.0
  - selenium/standalone-chrome:latest

stages:
  - test
  - precompile

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: postgres
  RAILS_ENV: test
  DISABLE_SPRING: 1
  BUNDLE_PATH: vendor/bundle
  SELENIUM_URL: http://selenium__standalone-chrome:4444/wd/hub

test-job:
  stage: test
  cache:
    paths:
      - node_modules/
      - .yarn
      - vendor
      - public/packs-test
  before_script:
    - curl -sL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get update -qq && apt-get install -y -qq nodejs
    # Install yarn as outlined in (https://yarnpkg.com/lang/en/docs/install/#alternatives-stable)
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    # Make available in the current terminal
    - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
    - node -v
    - yarn -v
    - ruby -v
    - which ruby
    - gem install bundler -v 2.3.13
    - bundle install --jobs $(nproc)  "${FLAGS[@]}" --path vendor
    - yarn install
    # Database setup
    - bundle exec rails db:create db:schema:load --trace
  script:
    - bundle exec rspec spec

precompile-job:
  stage: precompile
  cache:
    paths:
      - node_modules/
      - .yarn
      - vendor
      - public/packs-test
  script:
    - bundle exec rake assets:precompile

