stages:
  - test

test-job:
    stage: test
    image: ruby:2.7.6
    services:
        - postgres:12.0
    variables:
        POSTGRES_USER: postgresql
        POSTGRES_PASSWORD: postgresql
        DB_USERNAME: postgresql
        DB_PASSWORD: postgresql
        DB_HOST: postgres
        RAILS_ENV: test
        DISABLE_SPRING: 1
        BUNDLE_PATH: vendor/bundle
    script:
        - gem install bundler -v 2.3.13
        - bundle install
        - bundle exec rails db:create db:schema:load --trace
        - bundle exec rspec spec