version: '3'
services:
  app:
    build: .
    volumes:
      - ./tmp/pids:/app/tmp/pids
    # - ./entrypoint.sh:/app/entrypoint.sh
    # - ./db/seeds.rb:/app/db/seeds.rb
    #   - .:/app
    #   - bundle:/usr/local/bundle
    #   - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:decidim@db/decidim
      - SECRET_KEY_BASE=my-key-secret
      - DECIDIM_FORCE_SSL=false
      - QUEUE_ADAPTER=sidekiq
      - REDIS_URL=redis://redis:6379/1
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    volumes:
    # - ./entrypoint.sh:/app/entrypoint.sh
    #   - .:/app
    #   - bundle:/usr/local/bundle
    #   - node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:decidim@db/decidim
      - SECRET_KEY_BASE=my-key-secret
      - DECIDIM_FORCE_SSL=false
      - QUEUE_ADAPTER=sidekiq
      - REDIS_URL=redis://redis:6379/1
      - RUN_SIDEKIQ=true
    depends_on:
      - redis
  db:
    image: postgres:13
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=decidim
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  pg_data:
  redis_data:
  # bundle:
  # node_modules: