:concurrency: 5
:queues:
  - [mailers, 4]
  - [default, 2]
  - [newsletter, 2]
  - [newsletters_opt_in, 2]
  - [conference_diplomas, 2]
  - [decidim_events, 2]
  - [events, 2]
  - [user_report, 2]
  - [block_user, 2]
  - [exports, 2]
  - [translations, 2]
  - [close_meeting_reminder, 1]
  - [metrics, 1]
  - [reminders, 1]

