name: "[CI] Decidim"
on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.0.6
  NODE_VERSION: 16.19.1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis:3.2-alpine
        ports: ["6379:6379"]
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
            
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 119.0.6045.105

      - name: List Chrome
        run: apt list --installed | grep chrome

      - name: Remove Chrome
        run: sudo apt remove google-chrome-stable

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 119.0.6045.105
          
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup & create Database
        run: |
          bundle exec rails db:create db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      - name: Precompile assets
        run: |
          npm ci
          bundle exec rake assets:precompile
        env:
          RAILS_ENV: test

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres